name: Catch Record API Tests on GitHub

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod
  workflow_call:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: false
        type: string
        default: 'test'
jobs:
  api-tests:
    name: Catch Record API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./catch-record-tests
        with:
          project: api
          env: ${{ inputs.env }}
