name: Run Journey Tests on GitHub

permissions:
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod
      browser:
        description: 'Browser to run UI tests on'
        required: true
        default: 'Chromium'
        type: choice
        options:
          - Chromium
          - all
          - Chrome
          - Edge
          - Firefox
          - Safari
  workflow_call:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: false
        type: string
        default: 'test'
      browser:
        description: 'Browser to run UI tests on'
        required: false
        type: string
        default: 'Chromium'
    secrets:
      CATCH_RECORDING_EMAIL:
        required: false
      CATCH_RECORDING_PASSWORD:
        required: false
      CATCH_RECORDING_API_TOKEN:
        required: false
jobs:
  ui-tests:
    name: Run UI Journey Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-journey-tests
        with:
          project: ui
          env: ${{ inputs.env }}
          browser: ${{ inputs.browser }}
          email: ${{ secrets.CATCH_RECORDING_EMAIL }}
          password: ${{ secrets.CATCH_RECORDING_PASSWORD }}

  api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./run-journey-tests
        with:
          project: api
          env: ${{ inputs.env }}
          api-token: ${{ secrets.CATCH_RECORDING_API_TOKEN }}
          api-base-url: ${{ vars.CATCH_RECORDING_API_BASE_URL }}
