name: Catch Record UI Tests on GitHub

permissions:
  id-token: write
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - prod
      browser:
        description: 'Browser to run UI tests on'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - Chrome
          - Edge
          - Firefox
          - Safari
          - Mobile iOS
          - Mobile Android
  workflow_call:
    inputs:
      env:
        description: 'Environment to run tests against'
        required: false
        type: string
        default: 'test'
      browser:
        description: 'Browser to run UI tests on'
        required: false
        type: string
        default: 'all'
jobs:
  ui-tests:
    name: Catch Record UI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./catch-record-tests
        with:
          project: ui
          env: ${{ inputs.env }}
          browser: ${{ inputs.browser }}
